In [2]:
a = np.array([1, 2, 3]) #１次元配列

In [3]:
a

array([1, 2, 3])

In [4]:
print(a) #要素を表示

[1 2 3]


In [5]:
type(a) #型を確認

numpy.ndarray

In [6]:
a.shape #要素数を確認

(3,)

In [7]:
b = np.array([[1, 2, 3], [4, 5, 6]]) #２次元配列

In [8]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
b.shape #要素数を表示

(2, 3)

In [12]:
c1 = np.array([0, 1, 2, 3, 4, 5])
c1

array([0, 1, 2, 3, 4, 5])

c2 = c1.reshape((2, 3))
c2

In [13]:
c2 = c1.reshape((2, 3)) #変形。
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
c2 = c1.reshape((2, 4)) #要素数が合わないとエラーを起こす。
c2

ValueError: cannot reshape array of size 6 into shape (2,4)

In [15]:
c3 = c2.ravel() #１次元配列に戻す
c3

array([0, 1, 2, 3, 4, 5])

In [16]:
c4 = c2.flatten() #copyを返す
c4

array([0, 1, 2, 3, 4, 5])